id: linkedin-content-generator
namespace: company.team

description: |
  Automated LinkedIn Content Generation Workflow
  
  This workflow generates engaging LinkedIn posts about AI, Automation, and Low-Code topics using:
  - LangChain 1.0 AI agents for content creation
  - Brave Search API for trending topics research
  - Google Gemini 2.5 Flash Image for visual content
  - LinkedIn API for automated posting
  - Google Sheets for theme tracking

labels:
  - key: project
    value: linkedin-automation
  - key: owner
    value: guilherme

triggers:
  - id: schedule_morning
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * MON-FRI"
    timezone: America/Sao_Paulo
    
  - id: schedule_afternoon
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 16 * * MON-FRI"
    timezone: America/Sao_Paulo

tasks:
  - id: working-directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      # Step 1: Clone GitHub Repository
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Guilherme-Silva-Lopes/linkedin-content-generator.git
        branch: main
      
      # Step 2: Setup Python Environment
      - id: setup_env
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: python:3.13-slim
        commands:
          - pip install --upgrade pip
          - pip install -r requirements.txt
        env:
          PYTHONUNBUFFERED: "1"
      
      # Step 3: Generate Content with AI Agent
      - id: generate_content
        type: io.kestra.plugin.scripts.python.Script
        containerImage: python:3.13-slim
        beforeCommands:
          - pip install --no-cache-dir -r requirements.txt
        script: |
          import sys
          sys.path.insert(0, 'scripts')
          from linkedin_agent import main
          main()
        env:
          PYTHONUNBUFFERED: "1"
          GOOGLE_API_KEY: "{{ kv('GOOGLE_API_KEY') }}"
          BRAVE_SEARCH_API_KEY: "{{ kv('BRAVE_SEARCH') }}"
          GOOGLE_SHEETS_CREDENTIALS: "{{ kv('GOOGLE_SHEETS_CREDENTIALS') }}"
          LINKEDIN_CONTENT_SPREADSHEET_ID: "{{ kv('LINKEDIN_CONTENT_SPREADSHEETS') }}"
        outputFiles:
          - linkedin_post.json
      
      # Step 4: Generate Image (OpenAI DALL-E)
      - id: generate_image
        type: io.kestra.plugin.scripts.python.Script
        containerImage: python:3.13-slim
        beforeCommands:
          - pip install --no-cache-dir -r requirements.txt
        inputFiles:
          linkedin_post.json: "{{ outputs.generate_content.outputFiles['linkedin_post.json'] }}"
        script: |
          import sys
          sys.path.insert(0, 'scripts')
          from openai_image_generator import main
          main()
        env:
          PYTHONUNBUFFERED: "1"
          OPENAI_API_KEY: "{{ kv('OPENAI_API_KEY') }}"
        outputFiles:
          - linkedin_post.json
          - image_result.json
          - linkedin_image.png
        allowFailure: true # Continue if image generation fails
      
      # Step 5: Publish to LinkedIn
      - id: publish_to_linkedin
        type: io.kestra.plugin.scripts.python.Script
        containerImage: python:3.13-slim
        beforeCommands:
          - pip install --no-cache-dir -r requirements.txt
        inputFiles:
          linkedin_post.json: "{{ outputs.generate_image.outputFiles['linkedin_post.json'] ?? outputs.generate_content.outputFiles['linkedin_post.json'] }}"
          linkedin_image.png: "{{ outputs.generate_image.outputFiles['linkedin_image.png'] }}"
        script: |
          import sys
          sys.path.insert(0, 'scripts')
          from linkedin_publisher import main
          main()
        env:
          PYTHONUNBUFFERED: "1"
          LINKEDIN_ACCESS_TOKEN: "{{ kv('LINKEDIN_ACCESS_TOKEN') }}"
          GOOGLE_SHEETS_CREDENTIALS: "{{ kv('GOOGLE_SHEETS_CREDENTIALS') }}"
          LINKEDIN_CONTENT_SPREADSHEET_ID: "{{ kv('LINKEDIN_CONTENT_SPREADSHEETS') }}"
        outputFiles:
          - publish_result.json
      
      # Step 6: Log Success
      - id: log_success
        type: io.kestra.plugin.core.log.Log
        message: |
          ✅ LinkedIn Post Published Successfully!
          Title: {{ outputs.publish_to_linkedin.vars.title ?? 'N/A' }}
          Image: {{ outputs.generate_image.outputFiles['linkedin_image.png'] is defined ? 'Yes' : 'No' }}
          Execution ID: {{ execution.id }}

errors:
  - id: error_notification
    type: io.kestra.plugin.core.log.Log
    message: |
      ❌ LinkedIn Content Generation Failed
      Execution ID: {{ execution.id }}
